### ISSUE TITLE
Mismatch between issue tab statistics and name search results

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#72]
When searching for names by issue, the number of search results aren't matching the statistics reported on the issues page. For example, the [issues tab for dataset 2054 currently shows 99 records for ID not unique](http://test.col.plus/dataset/2054/issues) and the [search results only have 2 records](http://test.col.plus/dataset/2054/names?issue=id%20not%20unique).

**Comment by gdower** [comment]
I [removed 45 duplicate infraspecies from the CoLDP testing dataset](https://github.com/Sp2000/data-testing/commit/f1de320a32448001b6bdbcd8b3d63b710cc83611), which reduced the "ID not unique" statistic on the [issues tab](http://test.col.plus/dataset/2054/issues) to 13, but [name search still only shows 2 records](http://test.col.plus/dataset/2054/names?issue=id%20not%20unique).

**Comment by mdoering** [comment]
@ayco-at-naturalis is the autoclose indexing bug fixed yet?

**Comment by mdoering** [comment]
could it be caused by https://github.com/Sp2000/colplus-backend/issues/201 ?

**Comment by ayco-at-naturalis** [comment]
I will look into this, but #201 has been solved (need to verify before closing the issue)

**Comment by mdoering** [comment]
if its solved can you please close it and point to the commit? Also, is it deployed and all reindexed?

**Comment by ayco-at-naturalis** [comment]
It's "solved" in the sense that the mybatis resulthandler is now closed, but I have not checked yet that this is cause of the count mismatch

**Comment by mdoering** [comment]
hm, I have reindex 2054 with the latest & fixed code but its still the same.
IdNotUnique also applies to references. Maybe thats the cause

**Comment by mdoering** [comment]
Indeed. The same issue is flagged for names, taxa and references.
Maybe we need to split the issue into 3 kinds.

In the case of 2054:
> The inserted dataset contains 9 duplicate nameIds
 - NeoNameID 20009
 - NeoNameID 1   (8 times)

> The inserted dataset contains 1 duplicate taxonIds
- NeoUsageID 20009

**Comment by mdoering** [comment]
For details like this it is best to search the Kibana logs directly:

https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col),query:(match:(environment:(query:col,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:dataset,negate:!f,type:phrase,value:'2054'),query:(match:(dataset:(query:'2054',type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(query_string:(analyze_wildcard:!t,query:Duplicate)),sort:!('@timestamp',desc))

**Comment by mdoering** [comment]
Actually the best in this case is to search the verbatim records directly cause they will always return all issues:
http://api.col.plus/dataset/2054/verbatim?issue=id%20not%20unique

The name usage search will only return issues for the taxon (or synonym), but not the name alone and reference
